version: "3.8"
services:
  mongo:
    image: l33tlamer/mongodb-without-avx:6.2.1
    restart: unless-stopped
    container_name: rag_mongo
    command: ["--bind_ip_all"]
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
    user: ${CURRENT_UID}
  broker:
    image: rabbitmq:3-management
    restart: unless-stopped
    container_name: rag_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672